import argparse
import shutil
from pathlib import Path

from ultralytics import YOLO

from config import (
    YOLO_DATA_ROOT,
    YOLO_CLASSES_FILE,
    YOLO_DATA_YAML,
    YOLO_MODEL_DIR,
    YOLO_MODEL_NAME,
    YOLO_BASE_MODEL,
    YOLO_RUNS_DIR,
)


def read_class_names() -> list[str]:
    """classes.txt에서 클래스 이름 목록을 읽어온다."""
    if not YOLO_CLASSES_FILE.exists():
        raise FileNotFoundError(f"[ERROR] 클래스 파일이 없습니다: {YOLO_CLASSES_FILE}")

    with YOLO_CLASSES_FILE.open("r", encoding="utf-8") as f:
        names = [line.strip() for line in f.readlines() if line.strip()]

    if not names:
        raise ValueError(f"[ERROR] {YOLO_CLASSES_FILE} 에 유효한 클래스 이름이 없습니다.")

    return names


def generate_data_yaml(class_names: list[str]) -> None:
    """YOLO 학습용 data.yaml을 자동 생성한다."""
    # 윈도우 경로를 YOLO가 이해할 수 있도록 슬래시(/)로 통일
    root_str = str(YOLO_DATA_ROOT).replace("\\", "/")

    yaml_text = f"""# Auto-generated by train_yolo.py
path: {root_str}

train: images/train
val: images/val

nc: {len(class_names)}
names: {class_names}
"""

    YOLO_DATA_YAML.write_text(yaml_text, encoding="utf-8")
    print(f"[INFO] data.yaml 생성 완료 → {YOLO_DATA_YAML}")


def clean_previous_runs_and_weights():
    """--reset 옵션일 때 이전 학습 결과 및 가중치를 삭제."""
    if YOLO_RUNS_DIR.exists():
        print(f"[INFO] 이전 runs 삭제: {YOLO_RUNS_DIR}")
        shutil.rmtree(YOLO_RUNS_DIR)

    weight_path = YOLO_MODEL_DIR / f"{YOLO_MODEL_NAME}.pt"
    if weight_path.exists():
        print(f"[INFO] 이전 모델 가중치 삭제: {weight_path}")
        weight_path.unlink()


def train_yolo(
    mode: str = "fresh",
    epochs: int = 50,
    imgsz: int = 640,
    batch: int = 16,
    device: str = "0",  # GPU 0, CPU 사용시 "cpu"
):
    """YOLO 학습 실행 함수."""

    class_names = read_class_names()
    generate_data_yaml(class_names)

    # 사용 모델 선택
    if mode == "fresh":
        # 프리트레인 모델에서 새로 학습
        print(f"[INFO] Fresh training from base model: {YOLO_BASE_MODEL}")
        model = YOLO(YOLO_BASE_MODEL)
    elif mode == "resume":
        # 이전에 학습된 우리 모델에서 이어서 학습
        weight_path = YOLO_MODEL_DIR / f"{YOLO_MODEL_NAME}.pt"
        if not weight_path.exists():
            raise FileNotFoundError(
                f"[ERROR] 재학습용 가중치를 찾을 수 없습니다: {weight_path}\n"
                "먼저 --mode fresh 로 초기 학습을 한 번 수행해 주세요."
            )
        print(f"[INFO] Resuming training from: {weight_path}")
        model = YOLO(str(weight_path))
    else:
        raise ValueError("mode는 'fresh' 또는 'resume' 중 하나여야 합니다.")

    # Ultralytics YOLO 학습 호출
    results = model.train(
        data=str(YOLO_DATA_YAML),
        epochs=epochs,
        imgsz=imgsz,
        batch=batch,
        device=device,
        project=str(YOLO_RUNS_DIR),
        name=YOLO_MODEL_NAME,
        exist_ok=True,  # 같은 이름이 있어도 덮어씀
    )

    # 학습 결과 디렉토리(예: runs/train/food_yolov8n)
    save_dir = Path(results.save_dir)
    best_weight = save_dir / "weights" / "best.pt"

    if not best_weight.exists():
        raise FileNotFoundError(f"[ERROR] best.pt를 찾을 수 없습니다: {best_weight}")

    # 우리 프로젝트 고정 경로로 복사
    final_weight_path = YOLO_MODEL_DIR / f"{YOLO_MODEL_NAME}.pt"
    shutil.copy2(best_weight, final_weight_path)
    print(f"[INFO] best.pt → {final_weight_path} 로 복사 완료")
    print("[INFO] YOLO 학습 완료!")


def main():
    parser = argparse.ArgumentParser(description="YOLOv8 Training Script")

    parser.add_argument(
        "--mode",
        type=str,
        default="fresh",
        choices=["fresh", "resume"],
        help="fresh: 프리트레인 모델에서 새 학습 / resume: 이전 학습 모델에서 이어서 학습",
    )
    parser.add_argument("--epochs", type=int, default=50, help="학습 epoch 수")
    parser.add_argument("--imgsz", type=int, default=640, help="입력 이미지 크기")
    parser.add_argument("--batch", type=int, default=16, help="배치 크기")
    parser.add_argument(
        "--device",
        type=str,
        default="0",
        help='사용 장치 (예: "0"=GPU0, "0,1"=멀티GPU, "cpu"=CPU)',
    )
    parser.add_argument(
        "--reset",
        action="store_true",
        help="이전 학습 결과 및 가중치 삭제 후 완전히 새로 학습",
    )

    args = parser.parse_args()

    if args.reset:
        clean_previous_runs_and_weights()

    train_yolo(
        mode=args.mode,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
    )


if __name__ == "__main__":
    main()
